[build]
	command = "CI=false npm install && cd client && npm i && CI= npm run build"
	functions = "functions"
	publish = "client/build"

[functions]
        node_bundler = "esbuild"
		external_node_modules = ["express", "mongodb"]